### ISSUE TITLE
Better node-to-node transfer

### ISSUE THREAD

**Issue by pancetta** [Parallel-in-Time/pySDC#118]
I'm pretty sure they way interpolation and restriction in time (i.e. between collocation nodes) is currently done is not a great idea, see [here](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/core/BaseTransfer.py#L67). @tlunet: Would you mind having a look at it? Can your interpolation routine make this better?

**Comment by tlunet** [comment]
I could try something using a common object for interpolation and quadrature ... PR incoming. But to be clear, the get_transfer_matrix_Q method define interpolation using the Lagrange interpolating polynomial, right @pancetta ?

**Comment by pancetta** [comment]
Exactly. Maybe this is all good and well, but if you have a better idea, shoot! This code is taken from `libpfasst`, I assume.

**Comment by tlunet** [comment]
So, what I imagine yet would be to centralize every Lagrange-based functionalities (quadrature matrix, interpolation and transfers operators) into one main `LagrangeInterpolator` class (which would be a homemade extended `BarycentricInterpolator` class), and it would be instantiated once the nodes of the collocation class are generated. Then, the other classes would simply use its functionalities to generate weights, QMatrix, transfers matrix, interpolation matrix, etc ... (see [here](https://gitlab.com/tlunet/pythag/-/blob/master/scripts/standalone/lagrange.py) for a reference class).

If you agree with that, then should I continue working with my forked repo, or create a `dev` branch in this repo and work on it ?

**Comment by pancetta** [comment]
I do STRONGLY agree with that. This sounds like a very clean structure, which would help this code. I'd prefer PRs from your fork.

**Comment by tlunet** [comment]
So with #135 there is now the possibility to base the Collocation class on the LagrangeApproximation class (rather than using a modified barycentric interpolator from scipy, see https://github.com/Parallel-in-Time/pySDC/blob/8562c7c25a5819ece7deef551e3f288138caafdf/pySDC/core/Collocation.py#L10-L30

This can be one quick modification, but @pancetta you'll have to ok with the new tolerance threshold that would be used for the tests, see [pySDC/playgrounds/lagrange/quad_error.ipynb](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/playgrounds/lagrange/quad_error.ipynb)

In my opinion, we could choose the "AUTO" approach for the barycentric weight computation ("FAST" by default, switch to the "STABLE" when overflow occurs with a large number of points), and compute the integration matrix with the "FEJER" quadrature rule. This would allow to set a tolerance threshold for the [collocation tests](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/tests/test_collocation.py) of 1e-13, which should work even for the equidistant distribution ...

**Comment by pancetta** [comment]
Holy Guacamole! I'm absolutely ok with that. Yet, do we really need the "FAST" variant? All runtimes I see in the notebook with the "FEJER" rule are below `1E-03`, so why bother?

**Comment by tlunet** [comment]
With "FEJER" quadrature rule for the QMatrix computation, barycentric weights computed with "FAST" actually minimizesthe error for equidistant nodes ... since the "STABLE" and "CHEBFUN" approaches rely on using logarithm and exponential (more memory and time consuming), they are more complicated and don't really bring an improvement from the "FAST" method ... hence the choice

**Comment by pancetta** [comment]
OK, so ;et's do "FAST" with "STABLE" as fallback, if thing go awry, just as you suggested! Looking forward to this.

**Comment by tlunet** [comment]
Ok then, I'll implement this in the SBahn on my way home ...

**Comment by pancetta** [comment]
Like a pro!

**Comment by pancetta** [comment]
Closed by #137
