### ISSUE TITLE
Tests fail for new collocation class

### ISSUE THREAD

**Issue by pancetta** [Parallel-in-Time/pySDC#119]
Looks like the new collocation classes still have issues:
https://github.com/Parallel-in-Time/pySDC/runs/5582155629?check_suite_focus=true#step:9:407
Any ideas, @tlunet ?

**Comment by tlunet** [comment]
Yep, I'm currently investigating this issue, see https://github.com/tlunet/pySDC/blob/sauron/pySDC/playgrounds/lagrange/quad_error.ipynb : there I conduct the tests many times, and plot the mean and maximum (dashed lines) error for both weights and quadrature matrix (ie, test_canintegratepolynomials and test_partialquadraturewithQ respectively).

The problem is that it depends on many components of the implementation (node computation, barycentric weights, integration of lagrange polynomials, etc ...). I also intend to add the previous implementation (before optimization), so we can select the optimal implementation (in terms of error VS performance), and set adapted error criterion for the test scripts.

Soo, in progress ... :sweat_smile:

**Comment by tlunet** [comment]
But looking more at the error log, seems to be some instantiation issue with the collocation class using spline ... :confused:

**Comment by tlunet** [comment]
Ok, now this is weird, since the tests passed on my forked repository : https://github.com/tlunet/pySDC/runs/5584440360?check_suite_focus=true

**Comment by pancetta** [comment]
Also, no errors anymore.. temporary glitch? Or stupid random variables?

**Comment by danielru** [comment]
Some of the tests that I wrote may use random numbers (can't remember anymore). If so, it is possible that very occasionally an unfortunate combination occurs that violates some threshold. Could that be it?

**Comment by tlunet** [comment]
Probably temporary glitch with the spline function from scipy, that could not initialize the spline interpolant. It did not concern the weight and quadrature error tested with polynomials generated from random numbers
