### ISSUE TITLE
Proofread Wiki article

### ISSUE THREAD

**Issue by brownbaerchen** [Parallel-in-Time/pySDC#189]
I started a wiki page on preconditioners. Since I cannot make a PR on the wiki repo. I need to open this issue instead for a more manual and cumbersome workflow.

Also, I find it noteworthy, that I cannot push local changes to wiki because I don't have permissions:
```
$ git push
ERROR: Permission to Parallel-in-Time/pySDC.wiki.git denied to brownbaerchen.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
But I can make changes to the wiki on the GitHub website...

**Comment by tlunet** [comment]
From the looks of it, it appears that pushing to the wiki repo is only authorized when you have right to push on the main repo. Since this is not very compatible with the github strategy of forks etc ..., I believe this will complicate this whole "wiki on SDC" things, especially if we want to motivate other people in the community to contribute. 

I could propose an other approach, that would break a bit the "everything in the same place" idea, but not necessarily in a bad way : we create a specific repo in parallel-in-time for theoretical aspect and discussions about SDC. The current discussions (in pySDC) would be moved to this new repo, and the current wiki would be then the main git repo. That way, people wanted to contribute to this community wiki could simply do fork and PR, and at least it would be separated from pySDC itself, which is simply one code (among others) that implement SDC.

And eventually (in the future), this new repo could serve to host the content of a community-based website on SDC (like the PinT website, for instance ...). But for now, using a markown-based approach is probably simpled and sufficient, I guess.

What do you think @brownbaerchen @pancetta @danielru ?

**Comment by pancetta** [comment]
`sdc-resources` or `sdc-wiki` or `sdc-info` or `sdc-supplement`?

**Comment by tlunet** [comment]
`sdc-wiki` :+1:

**Comment by tlunet** [comment]
Ok, just created the public repo [`sdc-wiki`](https://github.com/Parallel-in-Time/sdc-wiki), initialized with the preliminary content already in pySDC wiki. Next step would be to move the discussions below to the new repo :

- https://github.com/Parallel-in-Time/pySDC/discussions/173
- https://github.com/Parallel-in-Time/pySDC/discussions/174

https://github.com/Parallel-in-Time/pySDC/discussions/179 can stay on this repo (I believe) and https://github.com/Parallel-in-Time/pySDC/discussions/176 can be deleted. I don't have admin access to pySDC tho, so @pancetta could you do it when you have time ?

**Comment by pancetta** [comment]
Done.
