### ISSUE TITLE
`L.uold` will be overwritten when using assignment operator somewhere else

### ISSUE THREAD

**Issue by lisawim** [Parallel-in-Time/pySDC#448]
During the usage of the convergence controller ``EstimateEmbeddedError`` that uses the ``StoreUOld`` controller I noticed that the increment is directly computed as zero after the first iteration which could not be correct.  Then it seems like using the assignment operator overwrites the ``L.uold`` value when
```
L.u[m + 1][:] = P.solve_system(rhs, alpha, L.u[m + 1], L.time + L.dt * self.coll.nodes[m])
```
is applied.

Using the assignment operator ``[:]`` should be the correct way to assign correctly to the values of the data type but this leads then instead to kind of trouble of overwriting. Considering the different memory adresses of ``L.uold`` and ``L.u`` have shown that they are different which is weird. @brownbaerchen suggested me to accept this bug for the first time, but we both don't know how large the impact of this bug is. 

Since I don't have any plan where this bug could come from, I reproduced this bug for someone else on a [branch in my fork](https://github.com/lisawim/pySDC/tree/issue_store_uold) and running the file [playground_error.py](https://github.com/lisawim/pySDC/blob/issue_store_uold/pySDC/projects/DAE/run/playground_error.py) shows the things explained above.

**Comment by pancetta** [comment]
Ugh.. thanks for reporting. Is it zero AT the first iteration, AFTER the first iteration or after ALL iterations?

**Comment by brownbaerchen** [comment]
The issue seems to be that in the line that Lisa pasted above, both `L.u[m+1]` and `L.uold[m+1]` are changed to the same value when using the assignment operator. So the increment is always zero in that case. This defies all logic that I can comprehend and I would very much like to understand where this happens..

**Comment by pancetta** [comment]
Untested, but my hunch is that [this line](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/implementations/convergence_controller_classes/store_uold.py#L37) creates a link instead of a copy. Why? Because you're iterating over the nodes with `[:]` instead of in space. Not sure if that is true, but I think you need to explicitly create a new data type here instead. (like `P.dtype_u(L.u[m])`).

**Comment by brownbaerchen** [comment]
> Untested, but my hunch is that [this line](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/implementations/convergence_controller_classes/store_uold.py#L37) creates a link instead of a copy. Why? Because you're iterating over the nodes with `[:]` instead of in space. Not sure if that is true, but I think you need to explicitly create a new data type here instead. (like `P.dtype_u(L.u[m])`).

Good catch! I think you're right!

**Comment by pancetta** [comment]
Want to fix that or should I? We would also need a test checking that for "future us".

**Comment by pancetta** [comment]
Since I see you're already on it: note that we also need a test to make sure this does not happen again.
